install.packages("devtools")
require(devtools)
install_version("coda", version = "0.9-3", repos = "http://cran.us.r-project.org")
install_version("doParallel", version = "1.0.15", repos = "http://cran.us.r-project.org")
install_version("foreach", version = "1.5.0", repos = "http://cran.us.r-project.org")
install_version("iterators", version = "1.0.12", repos = "http://cran.us.r-project.org")
install_version("here", version = "0.1", repos = "http://cran.us.r-project.org")
install_version("gridExtra", version = "2.3", repos = "http://cran.us.r-project.org")
install_version("ggplot2", version = "3.3.2", repos = "http://cran.us.r-project.org")
install_version("tmvtnorm", version = "1.4-10", repos = "http://cran.us.r-project.org")
install_version("gmm", version = "1.6-5", repos = "http://cran.us.r-project.org")
install_version("sandwich", version = "2.5-1", repos = "http://cran.us.r-project.org")
install_version("Matrix", version = "1.2-18", repos = "http://cran.us.r-project.org")
install_version("mvtnorm", version = "1.1-1", repos = "http://cran.us.r-project.org")
install_version("Rcpp", version = "1.0.6", repos = "http://cran.us.r-project.org")
install_version("rootSolve", version = "1.8.2.1", repos = "http://cran.us.r-project.org")
install_version("deSolve", version = "1.28", repos = "http://cran.us.r-project.org")
install_version("MASS", version = "7.3-51.6", repos = "http://cran.us.r-project.org")
install_version("data.table", version = "1.13.4", repos = "http://cran.us.r-project.org")
install_version("viridis", version = "0.5.1", repos = "http://cran.us.r-project.org")
install_version("forcats", version = "0.5.0", repos = "http://cran.us.r-project.org")
